version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: food_chatbot_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Expose port to host
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
